modLoader = "javafml"
loaderVersion = "[47,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "titlebarchanger"
version = "${version}"
displayName = "TitlebarChanger"
authors = "Thal0rin"
description = "Minecraft mod that offers advanced customization of window appearance, including titlebar, title, and border colors. Full functionality is available only on Windows 11; on Windows 10, the mod's features are limited to changing the titlebar color to dark :)"
logoFile = "logo.png"

[[dependencies.titlebarchanger]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.titlebarchanger]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1]"
ordering = "NONE"
side = "CLIENT"

