modLoader = "javafml"
loaderVersion = "[2,)"
license = "GNU GPL 3.0"

[[mods]]
modId = "titlebarchanger"
version = "${version}"
displayName = "TitlebarChanger"
authors = "Thal0rin"
description = "Minecraft mod that offers advanced customization of window appearance, including titlebar, title, and border colors. Full functionality is available only on Windows 11; on Windows 10, the mod's features are limited to changing the titlebar color to dark :)"
logoFile = "logo.png"

[[dependencies.titlebarchanger]]
modId = "neoforge"
type = "required"
versionRange = "[21-beta,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.titlebarchanger]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "CLIENT"


[[mixins]]
config = "titlebarchanger.mixins.json"
